# This file configures AWS CodeBuild.
version: 0.2

env:
  variables:
    # Disable call to checkpoint.hashicorp.com to look for new versions of Packer.
    CHECKPOINT_DISABLE: 1
    PACKER_NO_COLOR: 1
    ANSIBLE_STDOUT_CALLBACK: debug
  parameter-store:
    # Put secret Ansible vars into a JSON-string SSM Parameter Store SecureString.
    GROUP_VARS: /techops/ansible_vars/common/group_vars
    # Enable git clone with a GitHub OAuth Token fetched from SSM Parameter Store.
    GITHUB_TOKEN: /techops/cloud-engineering/account-standup/accountconfig.githuboauthtoken

phases:
  install:
    commands:
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.2.4/packer_1.2.4_linux_amd64.zip && unzip packer.zip
      - echo "Installing git"
      - yum install -y git
  pre_build:
    commands:
      - mkdir -p ansible/{group_vars,roles}
      - echo "Place ansible parameters into group_vars/all"
      - echo "$GROUP_VARS" > ansible/group_vars/all
      - echo "Directly clone all repos for ansible roles here."
      - cd ansible/roles
      # Pass this in as parameters a custom requirements.yml for ansible-galxy, somehow...
      # Alternatively, build a zip and pull from S3.
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-sps-common.git --branch 0.2.7 common
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-time.git --branch 0.2.2 time
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-cloud-init.git --branch 0.0.13 cloud-init
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-authconfig.git --branch 1.3.2 authconfig
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-sudo.git --branch 0.0.7 sudo
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-snmpd.git --branch 0.2.5 snmpd
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-inventory.git --branch 1.1.6 inventory
      - git clone --single-branch --depth 1 https://$GITHUB_TOKEN@github.com/SPSCommerce/ansible-role-deploy-monitor.git --branch 1.2.2 deploy-monitor
      - cd ../..
      - echo "Validating Packer template"
      - ./packer validate packer.json
  build:          
    commands:
      - ./packer build packer.json | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
      - aws events put-events --entries file://ami_builder_event.json
      - echo "build completed on `date`"
artifacts:
  files:
    - ami_builder_event.json
    - build.log
  discard-paths: yes
