version: 0.2

env:
  variables:
    # Disable call to checkpoint.hashicorp.com to look for new versions of Packer.
    CHECKPOINT_DISABLE: 1
    PACKER_NO_COLOR: 1
    PACKER_LOG: 1
    USER: "ec2-user"
  parameter-store:
    # Put this secret into a secure variable.
    GROUP_VARS: /techops/ansible_vars/common/group_vars

phases:
  install:
    commands:
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.2.4/packer_1.2.4_linux_amd64.zip && unzip packer.zip
      - echo "Installing Ansible"
      - pip install -U pip
      - pip install -U setuptools ansible
  pre_build:
    commands:
      - echo "Validating Packer template"
      - ./packer validate packer.json
      - echo "Place ansible parameters into group_vars/all"
      - mkdir -p ansible/group_vars
      - echo "$GROUP_VARS" > ansible/group_vars/all
  build:
    commands:
      - sudo -u $USER ./packer build -debug packer.json | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
      - aws events put-events --entries file://ami_builder_event.json
      - echo "build completed on `date`"
artifacts:
  files:
    - ami_builder_event.json
    - build.log
  discard-paths: yes
