---

- hosts: localhost
  tasks:
    - group_by:
        key: os_{{ ansible_distribution }}
    - debug:
        msg: "ansible_distribution is {{ ansible_distribution }}"
        verbosity: 2

- hosts: os_Amazon
  gather_facts: False
  tasks:
    - debug:
        msg: "Set image_group=amazonlinux for compatibility with SPS' roles"
        verbosity: 2
    - set_fact:
        image_group: "amazonlinux"

- hosts: os_Ubuntu
  gather_facts: False
  tasks:
    - debug:
        msg: "Set image_group=ubuntu16 for compatibility with SPS' roles"
        verbosity: 2
    - set_fact:
        image_group: "ubuntu16"

- hosts: localhost
  gather_facts: False
  connection: local
  become: yes
  pre_tasks:
    - debug:
        msg: "image_group is {{ image_group }}"
        verbosity: 2
  roles:
    - common
    - yatesr.timezone
    - influxdata.chrony
    - cloud-init
    - authconfig
    - sudo
    - snmpd
    - inventory
    - deploy-monitor
