---

- hosts: localhost
  become: yes
  roles:
    - ansible-role-sps-common
    - yatesr.timezone
    - influxdata.chrony
    - ansible-role-cloud-init
    - ansible-role-authconfig
    - ansible-role-sudo
    - ansible-role-snmpd
    - ansible-role-deploy-monitor
