---


 # talk to all hosts just so we can learn about them
- hosts: localhost
  tasks:
    - group_by:
        key: os_{{ ansible_distribution }}
    - debug:
        msg: "ansible_distribution is {{ ansible_distribution }}"
        verbosity: 2

- hosts: os_amazon
  gather_facts: False
  tasks:
    - set_fact:
      image_group: amazonlinux

- hosts: localhost
  connection: local
  gather_facts: true    # gather OS info that is made available for tasks/roles
  become: yes           # majority of CIS tasks require root
  roles:
    - common
    - time
    - cloud-init
    - authconfig
    - sudo
    - snmpd
    - inventory
    - deploy-monitor
