---

- hosts: localhost
  become: yes
  roles:
    - ansible-role-sps-common
    - yatesr.timezone
    - influxdata.chrony
    - ansible-role-cloud-init
    - ansible-role-authconfig
    - ansible-role-sudo
    - ansible-role-snmpd
    - ansible-role-deploy-monitor

  pre_tasks:
    -
      name: |
        Set variable "image_group" to "amazonlinux"
        when "ansible_distribution" is "Amazon" and "ansible_distribution_version" is "2018.03",
        as required by various SPS roles."
      set_fact:
        image_group: "amazonlinux"
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_version == "2018.03"
    -
      name: |
        Set variable "image_group" to "amazonlinux2"
        when "ansible_distribution" is "Amazon" and "ansible_distribution_version" is "Candidate",
        as required by various SPS roles."
      set_fact:
        image_group: "amazonlinux2"
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_version == "Candidate"
    -
      name: |
        Set variable "image_group" to "ubuntu16"
        when "ansible_distribution" is "Ubuntu" and "ansible_distribution_version" is "16.04",
        as required by various SPS roles."
      set_fact:
        image_group: "ubuntu16"
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version == "16.04"
    -
      name: |
        Set variable "image_group" to "ubuntu18"
        when "ansible_distribution" is "Ubuntu" and "ansible_distribution_version" is "18.04",
        as required by various SPS roles."
      set_fact:
        image_group: "ubuntu18"
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version == "18.04"
    -
      name: "Remove conflicting ntp package on Amazon Linux version 2018.03, in order to install chrony without conflict."
      package:
        name: "ntp"
        state: "absent"
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_version == "2018.03"
