
---

- name: 'Include variables from OS-specific files, depending on the facts'
  hosts: 'localhost'
  tasks:
    - name: 'Debug print distro and distro version'
      debug:
        msg: "ansible_distribution: {{ ansible_distribution }}, ansible_distribution_version: {{ ansible_distribution_version }}"
        verbosity: 1

    - name: 'Gather OS-specific variables'
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
        - "{{ ansible_distribution }}.yml"


- name: 'First remove conflicting ntp packages, if applicable'
  gather_facts: 'no'
  hosts: 'localhost'
  become: 'yes'
  tasks:
    - name: 'Remove conflicting ntp package on Amazon Linux, in order to install chrony without conflict.'
      package:
        name: 'ntp'
        state: 'absent'
      when:
        - 'ansible_distribution == "Amazon"'


- name: 'Execute role influxdata.chrony'
  hosts: 'localhost'
  gather_facts: 'no'
  tasks:
    - include_role:
        name: 'influxdata.chrony'
      when:
        - 'ansible_distribution == "Amazon"'


- name: 'Install the timezone role'
  hosts: 'localhost'
  gather_facts: 'no'
  roles:
    - 'yatesr.timezone'


- name: 'Install the big boy role'
  hosts: 'localhost'
  gather_facts: 'no'
  become: 'yes'
  roles:
    - 'ansible-role-authconfig'


- name: 'Install the remaining roles'
  hosts: 'localhost'
  gather_facts: 'no'
  become: 'yes'
  roles:
    - 'ansible-role-sps-common'
    - 'ansible-role-cloud-init'
    - 'ansible-role-sudo'
    - 'ansible-role-snmpd'
    - 'ansible-role-deploy-monitor'
