---

- hosts: localhost
  tasks:
    - group_by:
        key: os_{{ ansible_distribution }}
    - debug:
        msg: "ansible_distribution is {{ ansible_distribution }}"
        verbosity: 2

- hosts: os_Amazon
  gather_facts: False
  tasks:
    - debug:
        msg: "Set image_group=amazonlinux for compatibility with SPS' roles"
        verbosity: 2
    - set_fact:
        image_group: "amazonlinux"

- hosts: os_Ubuntu
  gather_facts: False
  tasks:
    - debug:
        msg: "Set image_group=ubuntu16 for compatibility with SPS' roles"
        verbosity: 2
    - set_fact:
        image_group: "ubuntu16"

- hosts: localhost
  gather_facts: False
  become: yes
  pre_tasks:
    - debug:
        msg: "image_group is {{ image_group }}"
        verbosity: 2
    - debug:
        msg: "sudoers is {{ sudoers }}"
        verbosity: 2
    - debug:
        msg: "access_groups is {{ access_groups }}"
        verbosity: 2
    - debug:
        msg: "ldap_bind_user is {{ ldap_bind_user }}"
        verbosity: 2
    - name: "Absent package ntp for installation of chrony in role influxdata.chrony"
      package:
        name: "ntp*"
        state: "absent"
  roles:
    - ansible-role-sps-common
    - yatesr.timezone
    - influxdata.chrony
    - ansible-role-cloud-init
    - ansible-role-authconfig
    - ansible-role-sudo
    - ansible-role-snmpd
    - ansible-role-deploy-monitor
