---

- hosts: localhost
  become: yes
  roles:
    - ansible-role-sps-common
    - yatesr.timezone
    - influxdata.chrony
    - ansible-role-cloud-init
    - ansible-role-authconfig
    - ansible-role-sudo
    - ansible-role-snmpd
    - ansible-role-deploy-monitor

  pre_tasks:
    -
      name: "Gather OS-specific variables"
      include_vars: "{{ item }}"
      dir: "group_vars"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    -
      name: "Remove conflicting ntp package on Amazon Linux version 2018.03, in order to install chrony without conflict."
      package:
        name: "ntp"
        state: "absent"
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_version == "2018.03"
